# Generated by Django 4.1.3 on 2022-12-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
