# Generated by Django 4.1.3 on 2023-01-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goals_created_alter_goals_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalscomments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
