# Generated by Django 4.1.3 on 2023-01-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goalscomments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Низкий'), (3, 'Средний'), (4, 'Высокий'), (1, 'Критический')], default=3, verbose_name='Приоритет'),
        ),
    ]
