# Generated by Django 4.1.3 on 2023-01-10 05:00

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    User = apps.get_model("core", "User")  # загрузка той модели, которая была на момент миграции
    Board = apps.get_model("goals", "Board")
    BoardParticipant = apps.get_model("goals", "BoardParticipant")
    GoalsCategory = apps.get_model("goals", "GoalsCategory")

    with transaction.atomic():  # применение изменений одной транзакцией
        for user in User.objects.all():
            new_board = Board.objects.create(
                title="Мои цели",
                created=timezone.now(),
                updated=timezone.now(),
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=timezone.now(),
                updated=timezone.now(),
            )

            GoalsCategory.objects.filter(user=user).update(board=new_board)  # проставление категориям пользователя его доски́


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_board_alter_goalscategory_created_and_more'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
