# Generated by Django 4.1.3 on 2023-01-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='telegram_chat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.IntegerField(),
        ),
    ]
