# Generated by Django 4.1.3 on 2023-01-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='telegram_chat_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='telegram_user_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
